// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwtlwdbcfymjgkudjvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd3Rsd2RiY2Z5bWpna3VkanZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MjI5MjEsImV4cCI6MjA1MTA5ODkyMX0.bVlhouTLmECX9W1KU-Tlo_oENHwwrPdMfsiDOf1Dq3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);